### ISSUE TITLE
Rails app templates - Error when generating expert use template

### ISSUE THREAD

**Issue by elmerwu** [elasticsearch/elasticsearch-rails#276]
I ran the basic and pretty templates in sequence with no issue, however the expert template shows me this error while compiling:

    Reading articles from gzipped YAML...
     (0.1ms)  begin transaction
    SQL (0.3ms)  INSERT INTO "articles" ("abstract", "content", "created_at", "published_on", "shares", "title", "updated_at", "url") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["abstract", "What does the way you speak say about where you’re from? Answer the questions to see your personal dialect map."], ["content", ""]..."], ["created_at", "2014-10-29 20:04:42.496382"], ["published_on", "2013-12-20"], ["shares", 1], ["title", "How Y’all, Youse and You Guys Talk"], ["updated_at", "2014-10-29 20:04:42.496382"], ["url", "http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html"]]
     (2.3ms)  commit transaction
     (0.4ms)  rollback transaction
    rake aborted!
    ActiveRecord::StatementInvalid: SQLite3::SQLException: cannot rollback - no transaction is active: rollback transaction

When it completes I only have one article in the database and if I add a new one it does not show up on the search.  I'm not sure why this is happening, any advice?

**Comment by pprzetacznik** [comment]
I've got exactly the same problem.

**Comment by pprzetacznik** [comment]
I found solution for this one. You've got to have redis turned on before running ```rake db:seed```.

**Comment by elmerwu** [comment]
Thanks @pprzetacznik , but after I run rake db:seed, I still only see one article result.  I checked the database and there are 1000s of articles and comments too... I ran rake db:seed a few times so there might be some duplicates, but it should still be more than one article on the index page.

**Comment by karmi** [comment]
The `02-pretty` now fails with an error:

```
generate    kaminari:views
Could not find generator kaminari:views.
        gsub    app/views/kaminari/_paginator.html.erb
The template [https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/02-pretty.rb] could not be loaded. Error: No such file or directory @ rb_sysopen - /Users/karmi/Desktop/searchapp/app/views/kaminari/_paginator.html.erb
```

**Comment by pprzetacznik** [comment]
@karmi: to fix this you have to add ```gem 'kaminari'``` to the Gemfile before you run ```02-pretty``` template cause it's required.

Please remember to add this line before elasticsearch's gems.

**Comment by karmi** [comment]
Not exactly -- there's been an error in the template due to incorrect regexes (Rails updates), working on a fix.

**Comment by pprzetacznik** [comment]
I'm pretty sure I've seen the same error when I run this template without ```gem 'kaminari'``` in my ```Gemfile``` but of course I can be wrong.

**Comment by karmi** [comment]
Sure thing, but the real problem is that the template has a bug and doesn't insert it to the Gemfile :) There's not much use for a template if you'd have to manually fix it as a user :)

**Comment by pprzetacznik** [comment]
You're absolutely right.

**Comment by karmi** [comment]
Guys, I've pushed a fix for `02-pretty.rb`, can you please run them again, and ping me back?

We need some automated/mechanical test for the templates, to prevent users running into these kind of issues. I'll look into that.

**Comment by louim** [comment]
@karmi, I just got the same problem, checked your fix and still get the same problem. I found out that I got single quote instead of the double that your regex is trying to match, so the insertion doesn't happen.

All inserted gems look like this: `gem 'elasticsearch', git: 'git://github.com/elasticsearch/elasticsearch-ruby.git'`

**Comment by karmi** [comment]
@louim Grrr, thanks!, will improve the regex and push a fix today.
